{{- if .Values.ingress.create }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flyte-binary.fullname" . }}-grpc
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-binary.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl ( .Values.commonLabels | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.commonLabels }}
    {{- tpl ( .Values.ingress.commonLabels | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.grpc.abels }}
    {{- tpl ( .Values.ingress.grpc.labels | toYaml ) . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- tpl ( .Values.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.commonAnnotations }}
    {{- tpl ( .Values.ingress.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.grpc.annotations }}
    {{- tpl ( .Values.ingress.grpc.annotations | toYaml ) . | nindent 4 }}
    {{- end }}
spec:
  rules:
  - http:
      paths:
      {{- if .Values.ingress.grpc.extraPaths.prepend }}
      {{- tpl ( .Values.ingress.grpc.extraPaths.prepend | toYaml ) . | nindent 6 }}
      {{- end }}
      - backend:
          service:
            name: {{ include "flyte-binary.service.grpc.name" . }}
            port:
              number: {{ include "flyte-binary.service.grpc.port" . }}
        path: /flyteidl.service.AdminService
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.service.grpc.name" . }}
            port:
              number: {{ include "flyte-binary.service.grpc.port" . }}
        path: /flyteidl.service.AdminService/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.service.grpc.name" . }}
            port:
              number: {{ include "flyte-binary.service.grpc.port" . }}
        path: /flyteidl.service.DataProxyService
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.service.grpc.name" . }}
            port:
              number: {{ include "flyte-binary.service.grpc.port" . }}
        path: /flyteidl.service.DataProxyService/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.service.grpc.name" . }}
            port:
              number: {{ include "flyte-binary.service.grpc.port" . }}
        path: /flyteidl.service.AuthMetadataService
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.service.grpc.name" . }}
            port:
              number: {{ include "flyte-binary.service.grpc.port" . }}
        path: /flyteidl.service.AuthMetadataService/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.service.grpc.name" . }}
            port:
              number: {{ include "flyte-binary.service.grpc.port" . }}
        path: /flyteidl.service.IdentityService
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.service.grpc.name" . }}
            port:
              number: {{ include "flyte-binary.service.grpc.port" . }}
        path: /flyteidl.service.IdentityService/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.service.grpc.name" . }}
            port:
              number: {{ include "flyte-binary.service.grpc.port" . }}
        path: /grpc.health.v1.Health
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.service.grpc.name" . }}
            port:
              number: {{ include "flyte-binary.service.grpc.port" . }}
        path: /grpc.health.v1.Health/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.service.grpc.name" . }}
            port:
              number: {{ include "flyte-binary.service.grpc.port" . }}
        path: /flyteidl.service.SignalService
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "flyte-binary.service.grpc.name" . }}
            port:
              number: {{ include "flyte-binary.service.grpc.port" . }}
        path: /flyteidl.service.SignalService/*
        pathType: ImplementationSpecific
      {{- if .Values.ingress.grpc.extraPaths.append }}
      {{- tpl ( .Values.ingress.grpc.extraPaths.append | toYaml ) . | nindent 6 }}
      {{- end }}
    {{- if .Values.ingress.host }}
    host: {{ tpl .Values.ingress.host . | quote }}
    {{- end }}
{{- end }}
