name: Lint

on: push

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            flyteadmin: flyteadmin/**
            flytepropeller: flytepropeller/**
  lint:
    needs: changes
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.package }}
    steps:
      - name: Lint
        uses: flyteorg/flytetools/.github/workflows/lint.yml@master
