name: Lint

on: push

jobs:
  generate_matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    steps:
      - uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "**/+(.github)"
          foldersOnly: true
          format: csv
      - outputs:
          run: echo ${{ steps.get_changed.outputs.matrix }}
  lint:
    needs: generate_matrix
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test
        run: echo ${{ steps.get_changed.outputs.matrix }}
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: ${{ inputs.go-version }}
#      - name: Lint
#        run: cd ${{ matrix.component }} && make install && make lint