name: Lint

on: push

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            flyteadmin: flyteadmin/**
            flytepropeller: flytepropeller/**
  lint:
    needs: changes
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        # e.g. ['package1', 'package2'] if both package folders contains changes
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.package }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test
        run: echo ${{ matrix.package }}
      - name: Get changed folders
        run: |
          pwd

#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: ${{ inputs.go-version }}
#      - name: Lint
#        run: cd ${{ matrix.component }} && make install && make lint