name: Build & Push Sandbox Docker Image

on:
  pull_request:
    paths:
      - docker/**
      - charts/**
      - .github/workflows/sandbox.yml

jobs:
  trigger-sandbox-build:
    name: Sandbox build
    uses: ./buildx_build.yaml
    with:
      context: .
      dockerfile: docker/sandbox/Dockerfile
      repository: flyte-sandbox
      version: latest
      push: false
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
      FLYTE_BOT_USERNAME: ${{ secrets.FLYTE_BOT_USERNAME }}

  trigger-sandbox-lite-build:
    name: Sandbox lite build
    uses: ./buildx_build.yaml
    with:
      context: docker/sandbox-lite
      dockerfile:  docker/sandbox-lite/images/dockerfiles/k3s/Dockerfile
      repository: flyte-sandbox-lite
      version: latest
      push: false
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
      FLYTE_BOT_USERNAME: ${{ secrets.FLYTE_BOT_USERNAME }}

  trigger-single-binary-build:
    name: Single Binary build
    uses: ./buildx_build.yaml
    with:
      context: .
      dockerfile:  Dockerfile
      repository: flyte-single-binary
      version: latest
      push: false
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
      FLYTE_BOT_USERNAME: ${{ secrets.FLYTE_BOT_USERNAME }}

